### ISSUE TITLE
Error: Cannot find module 'fuse-box'

### ISSUE THREAD

**Issue by davidm-public** [fuse-box/fuse-box-vue-seed#15]
updated repo with `salita --update` no problems, runs fine.

Then, added this project: 
https://github.com/asvae/vue-component-tree
ie: `npm install -D vue-component-tree`

Now, running npm start again results in this:
```
/Users/davem/.nvm/versions/node/v8.9.4/bin/node /Users/davem/.nvm/versions/node/v8.9.4/lib/node_modules/npm/bin/npm-cli.js run start --scripts-prepend-node-path=auto

> fuse-box-vue-seed@1.0.0 start /Users/davem/Documents/github-projects/fuse-box-vue-seed
> node ./fuse.js

module.js:540
    throw err;
    ^

Error: Cannot find module 'fuse-box'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/<path removed>/fuse-box-vue-seed/fuse.js:11:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

how is this possible? 
all I did was `npm install -D vue-component-tree`

no change to the source code or any config files?

David

**Comment by nchanged** [comment]
Hi, please check if fusebox is installed at all. npm might have glitches out
